# Generated by Django 5.1.7 on 2025-03-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('organizer', 'Организатор'), ('participant', 'Обычный пользователь')], default='participant', max_length=20),
        ),
    ]
