# Generated by Django 5.1.7 on 2025-03-21 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_balance_wallettransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название приза')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='prizes/')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость (в ₽)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток (0 = нет)')),
            ],
        ),
        migrations.CreateModel(
            name='PrizeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.prize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_prizes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
