# Generated by Django 5.1.7 on 2025-03-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_bonustask_bonuscompletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prizeredemption',
            name='prize',
        ),
        migrations.RemoveField(
            model_name='prizeredemption',
            name='user',
        ),
        migrations.DeleteModel(
            name='Prize',
        ),
        migrations.DeleteModel(
            name='PrizeRedemption',
        ),
    ]
