# Generated by Django 5.1.7 on 2025-03-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_prizeredemption_prize_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название приза')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость (₽)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='prizes/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен для получения')),
            ],
        ),
    ]
