# Generated by Django 5.1.7 on 2025-03-23 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_bonustask_eventtask_taskcompletion'),
        ('users', '0011_prizeredemption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscompletion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.bonustask'),
        ),
        migrations.DeleteModel(
            name='BonusTask',
        ),
    ]
