# Generated by Django 5.1.7 on 2025-05-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_quizquestion_quizanswer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('user', 'question')},
        ),
    ]
