# Generated by Django 5.1.7 on 2025-06-01 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_series', models.CharField(max_length=10)),
                ('passport_number', models.CharField(max_length=10)),
                ('issued_by', models.CharField(max_length=255)),
                ('date_issued', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
