# Generated by Django 5.1.7 on 2025-06-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_organizerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='admin_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organizerapplication',
            name='admin_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='admin_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='admin_response',
            field=models.TextField(blank=True),
        ),
    ]
