# Generated by Django 5.1.7 on 2025-06-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_ticketmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('question', 'Вопрос'), ('promotion', 'Повышение статуса'), ('report', 'Жалоба на пользователя')], max_length=20),
        ),
    ]
