# Generated by Django 5.1.7 on 2025-03-15 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_time', models.DateTimeField(verbose_name='Начало этапа')),
                ('end_time', models.DateTimeField(verbose_name='Конец этапа')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='events.event')),
            ],
            options={
                'verbose_name': 'Этап мероприятия',
                'verbose_name_plural': 'Этапы мероприятия',
                'ordering': ['start_time'],
            },
        ),
    ]
