# Generated by Django 5.1.7 on 2025-03-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
