# Generated by Django 5.1.7 on 2025-03-19 11:18

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.event_image_upload_path),
        ),
    ]
