# Generated by Django 5.1.7 on 2025-03-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enable_tasks',
            field=models.BooleanField(default=True, verbose_name='Включить конкурсы и бонусные задания'),
        ),
    ]
